name: Java CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Run Checkstyle
        run: ./gradlew check

      - name: Run Tests
        run: ./gradlew test

      - name: Build JAR
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: java-practice6-jar
          path: build/libs/*.jar